### ISSUE TITLE
I can't see the print results at last !

### ISSUE THREAD

**Issue by Marryli** [aqibsaeed/Genetic-CNN#2]
I can't see the print results at last !
# print top-3 optimal solutions 
best_individuals = tools.selBest(popl, k = 3)
for bi in best_individuals:
    print(bi)
when I run it ,the result is nothing.
I need your help.Thanks.

**Comment by aqibsaeed** [comment]
Execution will take some time, as for each iteration of GA a CNN model will be trained from scratch. Make sure that all the steps execution complete before you print optimal solution.

**Comment by Marryli** [comment]
2017-04-16 

declihuifang 



发件人：Aqib <notifications@github.com>
发送时间：2017-04-16 04:38
主题：Re: [aqibsaeed/Genetic-CNN] I can't see the print results at last ! (#2)
收件人："aqibsaeed/Genetic-CNN"<Genetic-CNN@noreply.github.com>
抄送："Marryli"<Declihuifang@163.com>,"Author"<author@noreply.github.com>

Execution will take some time, as for each iteration of GA a CNN model will be trained from scratch. Make sure that all the steps execution complete before you print optimal solution.

**Comment by Marryli** [comment]
Thanks for your reply !
 
But when I run it ,the accuracy is always about 0.1. This is worse than the network before. What's wrong ? And what is your reslut?


2017-04-16 

declihuifang 



发件人：Aqib <notifications@github.com>
发送时间：2017-04-16 04:38
主题：Re: [aqibsaeed/Genetic-CNN] I can't see the print results at last ! (#2)
收件人："aqibsaeed/Genetic-CNN"<Genetic-CNN@noreply.github.com>
抄送："Marryli"<Declihuifang@163.com>,"Author"<author@noreply.github.com>

Execution will take some time, as for each iteration of GA a CNN model will be trained from scratch. Make sure that all the steps execution complete before you print optimal solution.
