### ISSUE TITLE
The accuracy is always 0.101 .

### ISSUE THREAD

**Issue by Marryli** [aqibsaeed/Genetic-CNN#3]
what can i do to solve this?
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
gen	nevals
0  	20    
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
1  	6     
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
2  	8     
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
('Accuracy: ', 0.101)
3       10

**Comment by aqibsaeed** [comment]
Refer to [paper](https://arxiv.org/abs/1703.01513) to see what strategies authors used.
