### ISSUE TITLE
training using GA compares with BP

### ISSUE THREAD

**Issue by EigenvectorOfFate** [aqibsaeed/Genetic-CNN#4]
Hello! I read the paper, you said 'It would be very interesting to incorporate the genetic algorithm to training the network structure and weights simultaneously.' Considering the genetic algorithm is computationally expensive, is it the good method to training with GA compares with BP.

**Comment by aqibsaeed** [comment]
Hi, I am not the author of the paper :) but your observation is correct. There is a method called [NEAT](https://www.cs.ucf.edu/~kstanley/neat.html) that simultaneously do both things, I would suggest you to look into that. Also, [this](https://arxiv.org/pdf/1703.00548.pdf) might be an interested read on evolving deep architectures.
Using GA just for weight optimization is not good compare to BP that's what have been seen so far in practice.

**Comment by EigenvectorOfFate** [comment]
Thanks a lot.
