### ISSUE TITLE
Execution time

### ISSUE THREAD

**Issue by iamc1oud** [aqibsaeed/Genetic-CNN#5]
How much time does it take to execute? Cause it is taking too much time on my NVIDIA MX130 GPU.

**Comment by aqibsaeed** [comment]
It will take quite long depending on the hyper-parameters for the GA. Try to reduce the generation and population size.

**Comment by iamc1oud** [comment]
I am working on a project in which I had to use your code. Can I ping you
if I face any problem?

**Comment by aqibsaeed** [comment]
I would suggest asking questions on the blog post. I will try to respond as soon as I can.

**Comment by aqibsaeed** [comment]
Sorry I meant via email.
