### ISSUE TITLE
Make special Setting for boosting performance on MNSIT

### ISSUE THREAD

**Issue by ShipXu** [aqibsaeed/Genetic-CNN#7]
Hi, aqibsaeed,
I'm doing some research about NAS recently.
I noticed your implementation for GeneticCNN, which is awesome.
But I notice that the parameter setting in your Code is not suitable for MNIST（chanel is too small, and kernel size for pooling is very large）, which leads to the result that the performance of it is not ineffective(accuracy stays in a low range).
So I forked your repo, and made some change for MNSIT.
Thank for your contribution.
Best,
ShipXu

**Comment by aqibsaeed** [comment]
Glad you found it useful, feel free to submit a pull request.

**Comment by ShipXu** [comment]
Again, thanks for your work, and I have sent the pull request about it.
